// Text overlay types
export type OverlayType = "narration" | "dialogue" | "caption";

export interface TextOverlay {
  type: OverlayType;
  text: string;
  /** Percentage from left (0-100) */
  x: number;
  /** Percentage from top (0-100) */
  y: number;
  /** Text anchor: where the overlay is positioned relative to x,y */
  anchor: "top-left" | "top-right" | "bottom-left" | "bottom-right" | "center";
  /** Max width as percentage of panel width (default 40) */
  maxWidthPercent?: number;
  /** Speaker name for dialogue bubbles */
  speaker?: string;
}

// Panel layout sizes
export type PanelLayout = "normal" | "wide" | "tall" | "large";

// Per-panel margin adjustments (pixels)
export interface PanelMargins {
  top?: number;
  right?: number;
  bottom?: number;
  left?: number;
}

// A single comic panel
export interface ComicPanel {
  panelIndex: number;
  artworkPrompt: string;
  sourceExcerpt: string;
  overlays: TextOverlay[];
  layout: PanelLayout;
  imageUrl?: string;
  panelMargins?: PanelMargins;
}

// A page of panels
export interface ComicPage {
  pageNumber: number;
  panels: ComicPanel[];
}

// Art style chosen by AI
export interface ArtStyle {
  name: string;
  description: string;
  colorPalette: string;
  renderingNotes: string;
}

// Full script generated by GPT
export interface ComicScript {
  title: string;
  slug: string;
  sourceUrl: string;
  artStyle: ArtStyle;
  totalPanels: number;
  pages: ComicPage[];
  /** URL to the raw AI-generated script JSON in blob storage */
  scriptUrl?: string;
}

// Article manifest stored in Vercel Blob
export interface ArticleManifest {
  title: string;
  slug: string;
  sourceUrl: string;
  artStyle: ArtStyle;
  createdAt: string;
  totalPanels: number;
  pages: ComicPage[];
  /** URL to the raw AI-generated script JSON in blob storage */
  scriptUrl?: string;
}

// Article summary for the index
export interface ArticleIndexEntry {
  title: string;
  slug: string;
  sourceUrl: string;
  artStyleName: string;
  createdAt: string;
  totalPanels: number;
  pageCount: number;
  thumbnailUrl?: string;
}

// API request/response types
export interface GenerateScriptRequest {
  title: string;
  sourceUrl: string;
  articleText: string;
  password: string;
}

export interface GenerateScriptResponse {
  success: boolean;
  script?: ComicScript;
  error?: string;
}

export interface GeneratePanelRequest {
  artworkPrompt: string;
  artStyle: ArtStyle;
  slug: string;
  panelIndex: number;
  password: string;
}

export interface GeneratePanelResponse {
  success: boolean;
  imageUrl?: string;
  panelIndex?: number;
  error?: string;
}

export interface SaveArticleRequest {
  manifest: ArticleManifest;
  password: string;
}

export interface SaveArticleResponse {
  success: boolean;
  slug?: string;
  error?: string;
}

export interface DeleteArticleRequest {
  slug: string;
  password: string;
}

export interface DeleteArticleResponse {
  success: boolean;
  error?: string;
}
