// Text overlay types
export type OverlayType = "narration" | "dialogue" | "caption";

export interface TextOverlay {
  type: OverlayType;
  text: string;
  /** Percentage from left (0-100) */
  x: number;
  /** Percentage from top (0-100) */
  y: number;
  /** Text anchor: where the overlay is positioned relative to x,y */
  anchor: "top-left" | "top-right" | "bottom-left" | "bottom-right" | "center";
  /** Max width as percentage of panel width (default 40) */
  maxWidthPercent?: number;
  /** Speaker name for dialogue bubbles */
  speaker?: string;
  /** Where the speaking character is positioned in the panel (for audio marble placement) */
  characterPosition?: FocalPoint;
  /** URL to TTS audio clip in blob storage */
  audioUrl?: string;
}

// Panel layout sizes
export type PanelLayout = "normal" | "wide" | "tall" | "large";

// Where the main subject/focal point of the panel's composition is located.
// Used by the placement algorithm to put text AWAY from the focal point.
export type FocalPoint =
  | "center"
  | "left"
  | "right"
  | "top"
  | "bottom"
  | "top-left"
  | "top-right"
  | "bottom-left"
  | "bottom-right";

// Per-panel margin adjustments (pixels)
export interface PanelMargins {
  top?: number;
  right?: number;
  bottom?: number;
  left?: number;
}

// A single comic panel
export interface ComicPanel {
  panelIndex: number;
  artworkPrompt: string;
  sourceExcerpt?: string;
  overlays: TextOverlay[];
  layout: PanelLayout;
  /** Where the main visual subject is in this panel's composition */
  focalPoint?: FocalPoint;
  imageUrl?: string;
  panelMargins?: PanelMargins;
  /** Text-only panel — no image generated, overlays rendered on dark gradient background */
  textOnly?: boolean;
}

// A page of panels
export interface ComicPage {
  pageNumber: number;
  panels: ComicPanel[];
}

// Art style chosen by AI
export interface ArtStyle {
  name: string;
  description: string;
  colorPalette: string;
  renderingNotes: string;
}

// Full script generated by GPT
export interface ComicScript {
  title: string;
  slug: string;
  sourceUrl: string;
  artStyle: ArtStyle;
  totalPanels: number;
  pages: ComicPage[];
  /** URL to the raw AI-generated script JSON in blob storage */
  scriptUrl?: string;
}

// Voice profile for a character speaker
export interface CharacterVoiceProfile {
  speaker: string;
  voiceId: string;
  voiceDescription: string;
  isNarrator: boolean;
}

// Voice data for an entire article
export interface ArticleVoiceData {
  voices: CharacterVoiceProfile[];
  generatedAt: string;
}

// Article manifest stored in Vercel Blob
export interface ArticleManifest {
  title: string;
  slug: string;
  sourceUrl: string;
  artStyle: ArtStyle;
  createdAt: string;
  totalPanels: number;
  pages: ComicPage[];
  /** URL to the raw AI-generated script JSON in blob storage */
  scriptUrl?: string;
  /** Bumped when the placement algorithm changes; triggers re-placement on load */
  placementVersion?: number;
  /** True for articles generated with voice audio */
  audioEnabled?: boolean;
  /** Voice mapping data for audio-enabled articles */
  voiceData?: ArticleVoiceData;
  /** Generation status: generating (in progress), partial (has failures), complete (all done) */
  status?: "generating" | "partial" | "complete";
}

// Generation pipeline stages
export type GenerationStage =
  | "idle"
  | "script"
  | "editing"
  | "voices"
  | "panels"
  | "saving"
  | "done"
  | "error"
  | "partial";

// Interactive failure handling
export type UserDecision = "retry" | "skip" | "skip_section" | "terminate";
export type PipelineSection = "voice_creation" | "tts" | "panels";
export interface PendingDecision {
  section: PipelineSection;
  failedDetails: string[];
  succeededCount: number;
  failedCount: number;
  totalCount: number;
}

// Article summary for the index
export interface ArticleIndexEntry {
  title: string;
  slug: string;
  sourceUrl: string;
  artStyleName: string;
  createdAt: string;
  totalPanels: number;
  pageCount: number;
  thumbnailUrl?: string;
  status?: "generating" | "partial" | "complete";
}

// API request/response types
export interface GenerateScriptRequest {
  title: string;
  sourceUrl: string;
  articleText: string;
  password: string;
}

export interface GenerateScriptResponse {
  success: boolean;
  script?: ComicScript;
  error?: string;
}

export interface GeneratePanelRequest {
  artworkPrompt: string;
  artStyle: ArtStyle;
  slug: string;
  panelIndex: number;
  password: string;
  layout?: PanelLayout;
}

export interface GeneratePanelResponse {
  success: boolean;
  imageUrl?: string;
  panelIndex?: number;
  error?: string;
}

export interface SaveArticleRequest {
  manifest: ArticleManifest;
  password: string;
}

export interface SaveArticleResponse {
  success: boolean;
  slug?: string;
  error?: string;
}

export interface DeleteArticleRequest {
  slug: string;
  password: string;
}

export interface DeleteArticleResponse {
  success: boolean;
  error?: string;
}

export interface GenerateVoiceRequest {
  text: string;
  speaker: string;
  voiceId: string;
  slug: string;
  panelIndex: number;
  overlayIndex: number;
  password: string;
}

export interface GenerateVoiceResponse {
  success: boolean;
  audioUrl?: string;
  error?: string;
}

export interface DescribeVoicesRequest {
  speakers: string[];
  articleTitle: string;
  password: string;
}

export interface DescribeVoicesResponse {
  success: boolean;
  descriptions?: Record<string, string>;
  error?: string;
}

export interface CreateVoiceRequest {
  voiceDescription: string;
  speakerLabel: string;
  sampleText: string;
  password: string;
}

export interface CreateVoiceResponse {
  success: boolean;
  voiceId?: string;
  error?: string;
}
